-- Run this script to ENABLE all Audit Triggers --

ALTER TRIGGER TIGER."TRG_AUDIT_CARRIER_CUSTOMER" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_CUSTOMER" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_CUSTOMER_ORDER" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_EDI_FILE" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_IB_INVOICE" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_LN_ITM_CHARGE" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_LN_ITM_SUMMARY" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_OB_CUST_INVOICE" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_OB_CUST_INVOICE_INFO" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_PACKAGE" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_PARTY" ENABLE;

ALTER TRIGGER TIGER."TRG_AUDIT_SHIPMENT_INFO" ENABLE;