SET SERVEROUTPUT ON
SET LINESIZE 200
SET FEEDBACK OFF
SET VERIFY OFF
SET EMBEDDED ON
SET HEADING OFF
SPOOL &2 APPEND

PROMPT CREATE OR REPLACE TRIGGER TIGER."TRG_AUDIT_&1"
PROMPT BEFORE DELETE OR UPDATE ON &1
PROMPT FOR EACH ROW
PROMPT BEGIN
PROMPT IF UPDATING THEN
	SELECT '	TIGER.AUDIT_PKG.CREATE_AUDIT_MASTER_RECORD( ''&1'', :NEW.ID, ''U'' );' FROM DUAL;
PROMPT ELSE
	SELECT '	TIGER.AUDIT_PKG.CREATE_AUDIT_MASTER_RECORD( ''&1'', :OLD.ID, ''D'' );' FROM DUAL;
PROMPT END IF;;

SELECT '    TIGER.AUDIT_PKG.CHECK_AND_AUDIT( ''' || COLUMN_NAME || ''', ''' || DATA_TYPE || ''', ' || ':NEW.' || COLUMN_NAME || ', :OLD.' || COLUMN_NAME || ');'
FROM USER_TAB_COLUMNS WHERE TABLE_NAME = UPPER('&1')
/
PROMPT END;;
PROMPT /

SPOOL OFF
SET FEEDBACK ON
SET EMBEDDED OFF
SET HEADING ON
SET VERIFY ON
