#!/bin/sh

sqlplus tiger/kigertiger@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.20.0.191)(PORT=1521))(CONNECT_DATA=(SERVER=dedicated)(SID=wwdev)))" <<EOF

SET DEFINE ON
DEFINE outputfile = script-output/gentrgs.sql

@GENERATE_AUDIT_TRIGGER.sql CARRIER_CUSTOMER &outputfile
@GENERATE_AUDIT_TRIGGER.sql CUSTOMER &outputfile
@GENERATE_AUDIT_TRIGGER.sql CUSTOMER_ORDER &outputfile
@GENERATE_AUDIT_TRIGGER.sql EDI_FILE &outputfile
@GENERATE_AUDIT_TRIGGER.sql IB_INVOICE &outputfile
@GENERATE_AUDIT_TRIGGER.sql LN_ITM_CHARGE &outputfile
@GENERATE_AUDIT_TRIGGER.sql LN_ITM_SUMMARY &outputfile
@GENERATE_AUDIT_TRIGGER.sql OB_CUST_INVOICE &outputfile
@GENERATE_AUDIT_TRIGGER.sql OB_CUST_INVOICE_INFO &outputfile
@GENERATE_AUDIT_TRIGGER.sql PACKAGE &outputfile
@GENERATE_AUDIT_TRIGGER.sql PARTY &outputfile
@GENERATE_AUDIT_TRIGGER.sql SHIPMENT_INFO &outputfile

EOF